// <auto-generated />
namespace eform.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addFlowMainSubOverTimeForm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addFlowMainSubOverTimeForm));
        
        string IMigrationMetadata.Id
        {
            get { return "201807150832547_addFlowMain-Sub-OverTimeForm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
