// <auto-generated />
namespace eform.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addOther10InForumItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addOther10InForumItem));
        
        string IMigrationMetadata.Id
        {
            get { return "201903312136104_addOther10InForumItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
